"""Write source/certs.c from certs/*.pem (run from the repo root)."""
import pathlib

names = ["gts-root-r4", "globalsign-root-ca"]
body = "".join(pathlib.Path(f"certs/{n}.pem").read_text() for n in names)
out = [
    "// Generated by tools/embed_certs.py from certs/*.pem: trust anchors for",
    "// retroachievements.org (Cloudflare: WE1 -> GTS Root R4, cross-signed by",
    "// GlobalSign Root CA).",
    "#include <stddef.h>",
    "",
    "const char ra_ca_pem[] =",
]
out += ['\t"' + line + '\\n"' for line in body.splitlines()]
out[-1] += ";"
out.append("const size_t ra_ca_pem_len = sizeof(ra_ca_pem);")
pathlib.Path("source/certs.c").write_text("\n".join(out) + "\n", newline="\n")
